# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
