# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_imagerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
