# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20171127_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(blank=True, choices=[('DSLR', 'Digital Single Lens Reflex'), ('M', 'Mirrorless'), ('AC', 'Advanced Compact'), ('SLR', 'Single Lens Reflex')], max_length=4, null=True),
        ),
    ]
