# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20171129_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
