# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 00:39
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0006_auto_20171129_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photostyles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('blackandwhite', 'Black and White'), ('night', 'Night'), ('macro', 'Macro'), ('3d', '3D'), ('artistic', 'Artistic'), ('underwater', 'Underwater')], max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('weddings', 'Weddings'), ('headshots', 'HeadShots'), ('landscape', 'LandScape'), ('portraits', 'Portraits'), ('art', 'Art')], max_length=42, null=True),
        ),
    ]
