language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database imagersite;" -U postgres

#set some environment variables
env:
  - DB_NAME=imagersite DB_USER=postgres DB_HOST='127.0.0.1' SECRET_KEY='potato' DEBUG='True'

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# commands to run tests
script:
  - python imagersite/manage.py migrate
  - coverage run imagersite/manage.py test imagersite

after_success:
  - coveralls

notifications:
  email: false