# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20171129_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=180),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=180),
        ),
    ]
